package com.mycompany.calculatorswing.view;

import static com.mycompany.calculatorswing.model.CalculadoraSwing.canWrite;
import static com.mycompany.calculatorswing.model.CalculadoraSwing.clear;
import static com.mycompany.calculatorswing.model.CalculadoraSwing.clearZero;
import static com.mycompany.calculatorswing.model.CalculadoraSwing.cube;
import static com.mycompany.calculatorswing.model.CalculadoraSwing.delete;
import static com.mycompany.calculatorswing.model.CalculadoraSwing.division;
import static com.mycompany.calculatorswing.model.CalculadoraSwing.getOperation;
import static com.mycompany.calculatorswing.model.CalculadoraSwing.getSolution;
import static com.mycompany.calculatorswing.model.CalculadoraSwing.getValue1;
import static com.mycompany.calculatorswing.model.CalculadoraSwing.imputText;
import static com.mycompany.calculatorswing.model.CalculadoraSwing.multiply;
import static com.mycompany.calculatorswing.model.CalculadoraSwing.percent;
import static com.mycompany.calculatorswing.model.CalculadoraSwing.setOperation;
import static com.mycompany.calculatorswing.model.CalculadoraSwing.setValue1;
import static com.mycompany.calculatorswing.model.CalculadoraSwing.setValue2;
import static com.mycompany.calculatorswing.model.CalculadoraSwing.squareRoot;
import static com.mycompany.calculatorswing.model.CalculadoraSwing.squared;
import static com.mycompany.calculatorswing.model.CalculadoraSwing.sum;
import static com.mycompany.calculatorswing.model.CalculadoraSwing.sustrat;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        btnPowerThree = new javax.swing.JButton();
        btnPowerTwo = new javax.swing.JButton();
        btnSquareRoot = new javax.swing.JButton();
        btnPercentage = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnPi = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnPosOrNeg = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnSubtract = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnOne = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnSumatory = new javax.swing.JButton();
        btnClearScreen = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnEquals = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(400, 500));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWeights = new double[] {1.0, 1.0, 1.0, 1.0, 1.0};
        layout.rowWeights = new double[] {0.5, 1.0, 1.0, 1.0, 1.0, 1.0};
        getContentPane().setLayout(layout);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 25)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("0");
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jLabel1, gridBagConstraints);

        btnPowerThree.setText("x³");
        btnPowerThree.setBorderPainted(false);
        btnPowerThree.setPreferredSize(new java.awt.Dimension(0, 0));
        btnPowerThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPowerThreeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnPowerThree, gridBagConstraints);

        btnPowerTwo.setText("x²");
        btnPowerTwo.setPreferredSize(new java.awt.Dimension(0, 0));
        btnPowerTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPowerTwoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnPowerTwo, gridBagConstraints);

        btnSquareRoot.setText("√");
        btnSquareRoot.setPreferredSize(new java.awt.Dimension(0, 0));
        btnSquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquareRootActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnSquareRoot, gridBagConstraints);

        btnPercentage.setText("%");
        btnPercentage.setPreferredSize(new java.awt.Dimension(0, 0));
        btnPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPercentageActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnPercentage, gridBagConstraints);

        btnDivision.setText("÷");
        btnDivision.setPreferredSize(new java.awt.Dimension(0, 0));
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnDivision, gridBagConstraints);

        btnPi.setText("π");
        btnPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnPi, gridBagConstraints);

        btnSeven.setText("7");
        btnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnSeven, gridBagConstraints);

        btnEight.setText("8");
        btnEight.setToolTipText("");
        btnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEightActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnEight, gridBagConstraints);

        btnNine.setText("9");
        btnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNineActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnNine, gridBagConstraints);

        btnMultiply.setText("×");
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnMultiply, gridBagConstraints);

        btnPosOrNeg.setText("+/-");
        btnPosOrNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosOrNegActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnPosOrNeg, gridBagConstraints);

        btnFour.setText("4");
        btnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnFour, gridBagConstraints);

        btnFive.setText("5");
        btnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnFive, gridBagConstraints);

        btnSix.setText("6");
        btnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnSix, gridBagConstraints);

        btnSubtract.setText("-");
        btnSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtractActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnSubtract, gridBagConstraints);

        btnDelete.setText("⌫");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnDelete, gridBagConstraints);

        btnOne.setText("1");
        btnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnOne, gridBagConstraints);

        btnTwo.setText("2");
        btnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnTwo, gridBagConstraints);

        btnThree.setText("3");
        btnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnThree, gridBagConstraints);

        btnSumatory.setText("+");
        btnSumatory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumatoryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnSumatory, gridBagConstraints);

        btnClearScreen.setText("CE");
        btnClearScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearScreenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnClearScreen, gridBagConstraints);

        btnZero.setText("0");
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnZero, gridBagConstraints);

        btnDot.setText(".");
        btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDotActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btnDot, gridBagConstraints);

        btnEquals.setText("=");
        btnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualsActionPerformed(evt);
            }
        });
        getContentPane().add(btnEquals, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPowerThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPowerThreeActionPerformed
        setValue1(jLabel1.getText());
        cube();
        jLabel1.setText(getSolution());
    }//GEN-LAST:event_btnPowerThreeActionPerformed

    private void btnSquareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquareRootActionPerformed
        setValue1(jLabel1.getText());
        squareRoot();
        jLabel1.setText(getSolution());
    }//GEN-LAST:event_btnSquareRootActionPerformed

    private void btnPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPercentageActionPerformed
        if(getValue1() != ""){
          
            if(jLabel1.getText().charAt(jLabel1.getText().length()-1) == '%')   jLabel1.setText(jLabel1.getText().substring(0, jLabel1.getText().length()-1));
            else                                                                jLabel1.setText(jLabel1.getText()+"%"); 
        }
    }//GEN-LAST:event_btnPercentageActionPerformed

    private void btnSumatoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumatoryActionPerformed
        setOperation("+");
        if(getValue1() == ""){
            setValue1(jLabel1.getText());
            jLabel1.setText("0");
        }
    }//GEN-LAST:event_btnSumatoryActionPerformed

    private void btnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourActionPerformed
        if(canWrite())  jLabel1.setText(imputText(jLabel1.getText(),'4'));
        jLabel1.setText(clearZero(jLabel1.getText()));
    }//GEN-LAST:event_btnFourActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
        if(canWrite())  jLabel1.setText(imputText(jLabel1.getText(),'0'));
        jLabel1.setText(clearZero(jLabel1.getText()));
    }//GEN-LAST:event_btnZeroActionPerformed

    private void btnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneActionPerformed
        if(canWrite())  jLabel1.setText(imputText(jLabel1.getText(),'1'));
        jLabel1.setText(clearZero(jLabel1.getText()));
    }//GEN-LAST:event_btnOneActionPerformed

    private void btnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoActionPerformed
        if(canWrite())  jLabel1.setText(imputText(jLabel1.getText(),'2'));
        jLabel1.setText(clearZero(jLabel1.getText()));
    }//GEN-LAST:event_btnTwoActionPerformed

    private void btnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreeActionPerformed
        if(canWrite())  jLabel1.setText(imputText(jLabel1.getText(),'3'));
        jLabel1.setText(clearZero(jLabel1.getText()));
    }//GEN-LAST:event_btnThreeActionPerformed

    private void btnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiveActionPerformed
        if(canWrite())  jLabel1.setText(imputText(jLabel1.getText(),'5'));
        jLabel1.setText(clearZero(jLabel1.getText()));
    }//GEN-LAST:event_btnFiveActionPerformed

    private void btnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixActionPerformed
        if(canWrite())  jLabel1.setText(imputText(jLabel1.getText(),'6'));
        jLabel1.setText(clearZero(jLabel1.getText()));
    }//GEN-LAST:event_btnSixActionPerformed

    private void btnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSevenActionPerformed
        if(canWrite())  jLabel1.setText(imputText(jLabel1.getText(),'7'));
        jLabel1.setText(clearZero(jLabel1.getText()));
    }//GEN-LAST:event_btnSevenActionPerformed

    private void btnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEightActionPerformed
        if(canWrite())  jLabel1.setText(imputText(jLabel1.getText(),'8'));
        jLabel1.setText(clearZero(jLabel1.getText()));
    }//GEN-LAST:event_btnEightActionPerformed

    private void btnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNineActionPerformed
        if(canWrite())  jLabel1.setText(imputText(jLabel1.getText(),'9'));
        jLabel1.setText(clearZero(jLabel1.getText()));
    }//GEN-LAST:event_btnNineActionPerformed

    private void btnPosOrNegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosOrNegActionPerformed
        if(canWrite()){
            if(jLabel1.getText().charAt(0) == '-')     jLabel1.setText(jLabel1.getText().substring(1));
            else                                            jLabel1.setText("-"+jLabel1.getText());
        }
    }//GEN-LAST:event_btnPosOrNegActionPerformed

    private void btnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDotActionPerformed
        if(canWrite() == !jLabel1.getText().contains("."))        jLabel1.setText(imputText(jLabel1.getText(),'.'));
    }//GEN-LAST:event_btnDotActionPerformed

    private void btnPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiActionPerformed
        if(canWrite())        jLabel1.setText("3.14159265359");
    }//GEN-LAST:event_btnPiActionPerformed

    private void btnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualsActionPerformed

        if(getValue1() != ""){
             
            if(jLabel1.getText().charAt(jLabel1.getText().length()-1) == '%'){
                setValue2(percent(jLabel1.getText()));
            }else{
                setValue2(jLabel1.getText());
            }
             switch(getOperation()){
                 case "+":
                     sum();
                     jLabel1.setText(getSolution());
                     break;
                 case "-":
                     sustrat();
                     jLabel1.setText(getSolution());
                     break;
                 case "*":
                     multiply();
                     jLabel1.setText(getSolution());
                     break;
                 case "/":
                     division();
                     jLabel1.setText(getSolution());
                     break;
             }
        }       
    }//GEN-LAST:event_btnEqualsActionPerformed

    private void btnPowerTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPowerTwoActionPerformed
        setValue1(jLabel1.getText());
        squared();
        jLabel1.setText(getSolution());
    }//GEN-LAST:event_btnPowerTwoActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(jLabel1.getText() != "0" && jLabel1.getText() != "-0" && canWrite())     jLabel1.setText(delete(jLabel1.getText()));
        if(jLabel1.getText() == "")                                                 jLabel1.setText("0");
        if(jLabel1.getText() == "-")                                                jLabel1.setText("-0");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearScreenActionPerformed
        jLabel1.setText("0");
        clear();
    }//GEN-LAST:event_btnClearScreenActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        setOperation("*");
        if(getValue1() == ""){
            setValue1(jLabel1.getText());
            jLabel1.setText("0");
        }
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractActionPerformed
        setOperation("-");
        if(getValue1() == ""){
            setValue1(jLabel1.getText());
            jLabel1.setText("0");
        }
    }//GEN-LAST:event_btnSubtractActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        setOperation("/");
        if(getValue1() == ""){
            setValue1(jLabel1.getText());
            jLabel1.setText("0");
        }
    }//GEN-LAST:event_btnDivisionActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearScreen;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEquals;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnPercentage;
    private javax.swing.JButton btnPi;
    private javax.swing.JButton btnPosOrNeg;
    private javax.swing.JButton btnPowerThree;
    private javax.swing.JButton btnPowerTwo;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnSquareRoot;
    private javax.swing.JButton btnSubtract;
    private javax.swing.JButton btnSumatory;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnZero;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
